const Map<String, String> arSA = {
  "title_System_Ar": "اسم النظام بالعربي",
  "title_System_EN": "اسم النظام انجليزي",
  "ADS": "بنر الاعلان",
  "Swedish": "السويدية",
  "Waiting": "انتظار",
  "Camera": "الكميرا",
  "Gallery": "الاستديو",
  "Save": "حفظ",
  "French": "فرنسي",
  "balance": "الرصيد",
  "Create Your System": "أنشئ نظامك",
  "Login": "تسجيل الدخول",
  "Error": "خطأ",
  "Wallet": "المحفظه",
  "review": "مراجعه الحساب",
  "Please enter all fields": "الرجاء تعبئه جميع الحقول",
  "successful": "ناجح",
  "The link has been sent to your email": "تم إرسال الرابط إلى بريدك الإلكتروني",
  "Rest password": "إعادة تعيين كلمة المرور",
  "Register Now": "سجل الان",
  "Click to login": "انقر لتسجيل الدخول",
  "Don't have an account? ": "ليس لديك حساب؟ ",
  "Enter Your Email": "أدخل بريدك الإلكتروني",
  "Enter Your Client Email": "أدخل بريد الإلكتروني لعميلك",
  "Email": "البريد الإلكتروني",
  "Password": "كلمة المرور",
  "You have an account? ": "لديك حساب؟ ",
  "Forgot password": "هل نسيت كلمة السر",
  "Sign in with Email and Password": "تسجيل الدخول باستخدام البريد الإلكتروني وكلمة المرور",
  "Login with Google": " تسجيل الدخول عبر جوجل ",
  "Enter Your Password": "ادخل رقمك السري",
  "Enter Your Number VAT": "ادخل رقمك الضريبي",
  "Number VAT": " رقمك الضريبي",
  "Privacy Policy": "سياسة الخصوصية",
  "Terms & Conditions": "الشروط والاحكام",
  "Totel Users": "عدد المستخدمين :",
  "Totel Invoices": "عدد الفواتير :",
  "Enter Your VAT %": "ادخل الضريبه المضافه %",
  "VAT %": "الضريبه المضافه %",
  "Copyright": "حقوق النشر 2022",
  "phone": "الجوال",
  "Enter Your Client name": "ادخل اسم العميل ",
  "Please enter mobile phone number": "الرجاء رقم إدخال الهاتف المحمول",
  "quick invoice": "فاتوره سريعه",
  "Enter Your Price": "ادخل السعر",
  "Price": "السعر",
  "Qty": "الكمية",
  "Years": "سنوات",
  "Months": "اشهر",
  "Enter country": "أدخل الدولة",
  "country": "الدولة",
  "delete": "حذف",
  "country: ": "الدولة :",
  "Last 7 days": "اخر 7 ايام",
  "name": "الاسم",
  "English": "الانجليزيه",
  "Arabic": "العربيه",
  "Users": "المستخدمون",
  "Confirm Details": "تأكيد التفاصيل",
  "No Details List To Display": "لا توجد قائمة تفاصيل للعرض",
  "Click on Plus Icon (+) to add new Details": "لانقر فوق رمز Plus (+) لإضافة تفاصيل جديدة",
  "Please enter the value": "الرجاء تعبئه الحقل",
  "Enter Your Client phone": "ادخل رقم الجوال",
  "Enter Your Merchant Name": "ادخل اسم التاجر",
  "Merchant Name": " اسم التاجر",
  "Create Invoice": "انشى الفاتوره",
  "Advanced invoice": "فاتوره متقدمه",
  "Please enter a valid mobile phone number": "الرجاء إدخال رقم هاتف محمول صحيح",
  "All rights Reserved": "كل الحقوق محفوظة",
  "Please enter email": "الرجاء إدخال البريد الإلكتروني",
  "please enter a working email address": "الرجاء إدخال بريد إلكتروني صحيح",
  "Please enter the password": "الرجاء إدخال كلمة المرور",
  "Register Team account": "تسجيل حساب الفريق",
  "Enter username": "ادخل اسم المستخدم",
  "username": "اسم المستخدم",
  "Enter Your Full Name": "أدخل اسمك الكامل",
  "Enter Your Phone Number": "أدخل رقم هاتفك",
  "Full Name": " اسمك الكامل",
  "Pay": "ادفع ",
  "description": "الوصف",
  "Payment Done!": "انتهى الدفع!",
  "Change Language": "تغيير اللغة",
  "Delete Account": "حذف الحساب",
  "Merchent Name": "اسم التاجر :",
  "Total: ": "المجموع : ",
  "User not found": "المستخدم ليس موجود",
  "Wrong password": "كلمة مرور خاطئة",
  "Invoice To :": "فاتوره الي : ",
  "invoice date :": "تاريخ الفاتوره : ",
  "discount %": "تخفيض %",
  "Dashboard": "لوحه التحكم",
  "Support": "الدعم الفني",
  "Dashboard/Profile": "لوحه التحكم/الملف الشخصي",
  "Support/Profile": "الدعم الفني/الملف الشخصي",
  "Dashboard/Notifications": "لوحه التحكم/الاشعارات",
  "/Profile": "/الملف الشخصي",
  "Profile": "الملف الشخصي",
  "Settings": "الاعدادات",
  "System setting": "اعدادات النظام",
  " ADMIN": "اداره",
  "Log out": "تسجيل الخروج",
  "ADD Users": "اضافه مستخدين",
  "Date created: ": "تاريخ الانشاء : ",
  "Notifications": "الاشعارات",
  " MASTAR": " ماستر ",
  " USER": " مستخدم ",
  "Phone Number": "رقم الهاتف",
  "Account Status :": "حاله الحساب :",
  " Active": "مفعل ",
  "Total Today:": " المجموع اليوم: ",
  "You have no invoices": "ليس لديك فواتير ",
  " Under review": " قيد المراجعة ",
  "You have no notifications": "ليس لديك اشعارات",
  "ADD Details": "إضافة التفاصيل",
  "chart": "رسم بياني",
  "Pay Done": "انتهى الدفع",
  "In Review": "في مراجعة",
  "Unpaid": "غير مدفوعه",
  "Return": "إرجاع",
  "Search": "بحث",
  "No Online Support": "لا يوجد دعم متصل الان",
  "There are no Users": "ليس لديك مستخدمين",
  "Account Status :-": "حالة الحساب :-",
  "#Reference Number: ": "# رقم المرجع : ",
  "Total Invoice : ": "مجموع الفواتير : ",
  "Team management": "ادارة الفريق",
  "Account temporarily locked": "الحساب مغلق مؤقتًا",
  "created successfully, Your account in now under review": "تم إنشاؤه بنجاح ، حسابك قيد المراجعة الآن",
  "Your account has been deleted": "لقد تم حذف حسابك",
  "Something went wrong": "هناك خطأ ما",
  "the email is already used": "البريد الإلكتروني مستخدم بالفعل",
  "Your account has been disabled": "تم تعطيل حسابك",
  "Something went wrong! Please try again later": "هناك خطأ ما! الرجاء معاودة المحاولة في وقت لاحق",
  "Disabled": "معطل",
  "disable": "تعطيل",
  "Active": "مفعل",
  "Deleted": "محذوف",
  "User ID: ": "معرف المستخدم:",
  "Send": "إرسال:",
  "Amounts available": "المبالغ المتوفره:",
  "Refunds": "المبالغ المعاده:",
  "Total hold Amount": "إجمالي المبلغ المعلق:",
  "Amount withdrawn": "مبلغ تم سحبه:",
  "Enter title": "أدخل العنوان:",
  "title": " العنوان:",
  "Phone: ": " رقم الجوال:",
  "Email: ": " البريد الاكتروني :",
  "Enter details": "أدخل التفاصيل",
  "details": " التفاصيل",
  "Revenue: ": " الربح : ",
  "Status:": " حاله الحساب :",
  "User name: ": "اسم المستخدم:",
  "Send notifications": "إرسال الاشعارات",
  "User Type:-": "نوع المستخدم:-",
  "withdraw money": "سحب مبلغ",
  "deposit": "ايداع",
  "Withdrawal": "سحب",
  "Refund": "إعادة مال",
  "hold": "محجوز",
  "Please enter a valid valid password more than 8 numbers and letters": "الرجاء إدخال كلمة مرور صالحة أكثر من 8 أرقام وحروف",
};

const Map<String, String> enUS = {
  "title_System_Ar": "title_System_Ar",
  "No Details List To Display": "No Details List To Display",
  "country": "country",
  "Swedish": "Swedish",
  "hold": "hold",
  "French": "French",
  "Withdrawal": "Withdrawal",
  "Refund": "Refund",
  "deposit": "deposit",
  "withdraw money": "withdraw money",
  "Total hold Amount": "Total hold Amount",
  "ADD Users": "ADD Users",
  "Date created: ": "Date created: ",
  "delete": "delete",
  "Amount withdrawn": "Amount withdrawn",
  "Refunds": "Refunds",
  "country: ": "country: ",
  "Revenue: ": "Revenue: ",
  "details": "details",
  "title": "title",
  "Email: ": "Email: ",
  "disable": "disable",
  "Phone: ": "Phone: ",
  "Enter details": "Enter details",
  "Send": "Send",
  "Enter title": "Enter title",
  "User name: ": "User name: ",
  "User Type:-": "User Type:-",
  "Account Status :-": "Account Status :-",
  "chart": "chart",
  "Send notifications": "Send notifications",
  "No Online Support": "There is no online support right now",
  "Unpaid": "Unpaid",
  "There are no Users": "There are no Users",
  "Return": "Return",
  "Search": "Search",
  "In Review": "In Review",
  "#Reference Number: ": "# Reference Number: ",
  "Total Invoice : ": "Total Invoices : ",
  "Pay Done": "Pay Done",
  "Total Today:": "Total Today: ",
  "You have no invoices": "You have no invoices",
  "You have no notifications": "You have no notifications",
  "Dashboard/Notifications": "Dashboard/Notifications",
  "Enter Your Full Name": "Enter Your Full Name",
  "Full Name": "Full Name",
  "Team management": "Team management",
  "System setting": "System Setting",
  "Phone Number": "Phone Number",
  "Enter Your Phone Number": "Enter Your Phone Number",
  " MASTAR": " MASTAR",
  "Account Status :": "Account Status :",
  " ADMIN": "ADMIN",
  " USER": " USER",
  " Active": " Active",
  "Disabled": "Disabled",
  "Active": "Active",
  "Deleted": "Deleted",
  " Under review": "  Under review",
  "Notifications": "Notifications",
  "Settings": "Settings",
  "User ID: ": "User ID: ",
  "Delete Account": "Delete Account",
  "Profile": "Profile",
  "Status:": "Status:",
  "/Profile": "/Profile",
  "Support": "Support",
  "Dashboard/Profile": "Dashboard/Profile",
  "Support/Profile": "Support/Profile",
  "Dashboard": "Dashboard",
  "English": "English",
  "Something went wrong! Please try again later": "Something went wrong! Please try again later",
  "created successfully, Your account in now under review": "created successfully, Your account in now under review",
  "Qty": "Qty",
  "Arabic": "Arabic",
  "the email is already used": "the email is already used",
  "Account temporarily locked": "Account temporarily locked",
  "Wrong password": "Wrong password",
  "Your account has been disabled": "Your account has been disabled",
  "Pay": "Pay",
  "Payment Done!": "Payment Done!",
  "Merchent Name": "Merchent Name : ",
  "Invoice To :": "Invoice To :",
  "invoice date :": "invoice date :",
  "discount %": "discount %",
  "description": "description",
  "ADD Details": "ADD Details",
  "Total: ": "Total: ",
  "Click on Plus Icon (+) to add new Details": "Click on Plus Icon (+) to add new Details",
  "Confirm Details": "Confirm Details",
  "Enter country": "Enter country",
  "username": "username",
  "Enter username": "Enter username",
  "balance": "balance",
  "Log out": "Log out",
  "Register Team account": "Register Team account",
  "Wallet": "Wallet",
  "Amounts available": "Amounts available",
  "Please enter mobile phone number": "Please enter mobile phone number",
  "Please enter a valid mobile phone number": "Please enter a valid mobile phone number",
  "title_System_EN": "title_System_EN",
  "ADS": "ADS",
  "Please enter the value": "Please enter the value",
  "Last 7 days": "Last 7 days",
  "Months": "Months",
  "Years": "Years",
  "Enter Your Client Email": "Enter Your Client Email",
  "name": "name",
  "Enter Your Client name": "Enter Your Client name",
  "Price": "Price",
  "Enter Your Price": "Enter Your Price",
  "Advanced invoice": "Advanced invoice",
  "phone": "phone",
  "quick invoice": "quick invoice",
  "Enter Your Client phone": "Enter phone",
  "Create Invoice": "Create Invoice",
  "Save": "Save",
  "Merchant Name": "Merchant Name",
  "Number VAT": "Number VAT",
  "Enter Your VAT %": "Enter Your VAT %",
  "VAT %": "VAT %",
  "Enter Your Merchant Name": "Enter Your Merchant Name",
  "review": "review Acc",
  "Enter Your Number VAT": "Enter Your Number VAT",
  "Please enter all fields": "Please enter all fields",
  "Camera": "Camera",
  "Gallery": "Gallery",
  "Change Language": "Change Language",
  "Waiting": "Waiting",
  "Error": "Error",
  "Your account has been deleted": "Your account has been deleted",
  "The link has been sent to your email": "The link has been sent to your email",
  "successful": "successful",
  "User not found": "User not found",
  "Something went wrong": "Something went wrong",
  "Create Your System": "Create Your System",
  "Login": "Login",
  "Don't have an account? ": "Don't have an account? ",
  "You have an account? ": "You have an account? ",
  "Sign in with Email and Password": "Sign in with Email and Password",
  "Rest password": "Rest password",
  "Register Now": "Register Now",
  "Click to login": "Click to login",
  "Enter Your Email": "Enter Your Email",
  "Email": "Email",
  "Password": "Password",
  "Enter Your country": "Enter Your country",
  "Forgot password": "Forgot password",
  "Login with Google": " Login with Google ",
  "Enter Your Password": "Enter Your Password",
  "Privacy Policy": "Privacy Policy",
  "Terms & Conditions": "Terms & Conditions",
  "Totel Users": "Number of Users: ",
  "Totel Invoices": "Number of Invoices: ",
  "Copyright": "Copyright 2022",
  "Users": "Users",
  "All rights Reserved": "All rights Reserved",
  "Please enter email": "Please enter email",
  "please enter a working email address": "please enter a working email address",
  "Please enter the password": "Please enter the password",
  "Please enter a valid valid password more than 8 numbers and letters": "Please enter a valid valid password more than 8 numbers and letters",
};

const Map<String, String> svSV = {
  "title_System_Ar": "title_System_Ar",
  "Swedish": "svenska",
  "Users": "Användare",
  "No Details List To Display": "Ingen detaljlista att visa",
  "country": "Land",
  "hold": "håll",
  "French": "franska",
  "Withdrawal": "Uttag",
  "Refund": "Återbetalning",
  "deposit": "deposition",
  "withdraw money": "ta ut pengar",
  "Total hold Amount": "Totalt hållbelopp",
  "ADD Users": "lägga till användare",
  "Date created: ": "Skapat datum: ",
  "delete": "radera",
  "Amount withdrawn": "Indraget belopp",
  "Refunds": "Återbetalningar",
  "country: ": "Land: ",
  "Revenue: ": "Inkomst: ",
  "details": "detaljer",
  "title": "rubrik",
  "Email: ": "E-post: ",
  "disable": "inaktivera",
  "Phone: ": "Telefon: ",
  "Enter details": "Ange detaljer",
  "Send": "Skicka",
  "Enter title": "Ange titel",
  "User name: ": "Användarnamn: ",
  "User Type:-": "Användartyp:-",
  "Account Status :-": "Konto Status :-",
  "chart": "Diagram",
  "Send notifications": "Skicka meddelanden",
  "No Online Support": "Ingen onlinesupport",
  "Unpaid": "Obetald",
  "There are no Users": "Det finns inga användare",
  "Return": "Lämna tillbaka",
  "Search": "Sök",
  "In Review": "Under granskning",
  "#Reference Number: ": "# Referensnummer: ",
  "Total Invoice : ": "Total faktura : ",
  "Pay Done": "Betala Klar",
  "Total Today:": "Totalt idag: ",
  "You have no invoices": "Du har inga fakturor",
  "You have no notifications": "Du har inga aviseringar",
  "Dashboard/Notifications": "Instrumentpanel/Aviseringar",
  "Enter Your Full Name": "Ange ditt fullständiga namn",
  "Full Name": "Fullständiga namn",
  "Team management": "Laghantering",
  "System setting": "Systeminställning",
  "Phone Number": "Telefonnummer",
  "Enter Your Phone Number": "Skriv in ditt telefonnummer",
  " MASTAR": " INFINITIV",
  "Account Status :": "Konto Status :",
  " ADMIN": "ADMINISTRATION",
  " USER": " ANVÄNDARE",
  " Active": " Aktiva",
  "Disabled": "Inaktiverad",
  "Active": "Aktiva",
  "Deleted": "raderade",
  " Under review": "  Under granskning",
  "Notifications": "Aviseringar",
  "Settings": "inställningar",
  "User ID: ": "användar ID: ",
  "Delete Account": "Radera konto",
  "Profile": "Profil",
  "Status:": "Status:",
  "/Profile": "/Profil",
  "Support": "Stöd",
  "Dashboard/Profile": "Instrumentpanel/profil",
  "Support/Profile": "Stöd/Profil",
  "Dashboard": "instrumentbräda",
  "English": "engelsk",
  "Something went wrong! Please try again later": "Något gick fel! Vänligen försök igen senare",
  "created successfully, Your account in now under review": "skapat framgångsrikt, Ditt konto granskas nu",
  "Qty": "Antal",
  "Arabic": "arabiska",
  "the email is already used": "e-postmeddelandet är redan använt",
  "Account temporarily locked": "Kontot är tillfälligt låst",
  "Wrong password": "Fel lösenord",
  "Your account has been disabled": "ditt konto har avaktiverats",
  "Pay": "Betala",
  "Payment Done!": "Betalning gjord!",
  "Merchent Name": "handlarens namn : ",
  "Invoice To :": "Fakturera till :",
  "invoice date :": "fakturadatum :",
  "discount %": "rabatt %",
  "description": "beskrivning",
  "ADD Details": "LÄGG TILL Detaljer",
  "Total: ": "Total: ",
  "Click on Plus Icon (+) to add new Details": "Klicka på plusikonen (+) för att lägga till nya detaljer",
  "Confirm Details": "Bekräfta detaljer",
  "Enter country": "Ange land",
  "username": "Användarnamn",
  "Enter username": "Skriv in ditt användarnamn",
  "balance": "balans",
  "Log out": "Logga ut",
  "Register Team account": "Registrera Team-konto",
  "Wallet": "Plånbok",
  "Amounts available": "Tillgängliga mängder",
  "Please enter mobile phone number": "Vänligen ange mobilnummer",
  "Please enter a valid mobile phone number": "Vad vänlig och skriv in ett giltigt mobilnummer",
  "title_System_EN": "title_System_EN",
  "ADS": "annonser",
  "Please enter the value": "Ange värdet",
  "Last 7 days": "Senaste 7 dagarna",
  "Months": "månader",
  "Years": "år",
  "Enter Your Client Email": "Ange din kunds e-postadress",
  "name": "namn",
  "Enter Your Client name": "Ange ditt kundnamn",
  "Price": "Pris",
  "Enter Your Price": "Ange ditt pris",
  "Advanced invoice": "Avancerad faktura",
  "phone": "telefon",
  "quick invoice": "snabb faktura",
  "Enter Your Client phone": "Ange din klienttelefon",
  "Create Invoice": "Skapa faktura",
  "Save": "Spara",
  "Merchant Name": "handlarens namn",
  "Number VAT": "Antal moms",
  "Enter Your VAT %": "Ange din momsprocent %",
  "VAT %": "MOMS %",
  "Enter Your Merchant Name": "Ange ditt säljarnamn",
  "review": "recension Acc",
  "Enter Your Number VAT": "Ange ditt nummer moms",
  "Please enter all fields": "Vänligen fyll i alla fält",
  "Camera": "Kamera",
  "Gallery": "Galleri",
  "Change Language": "Ändra språk",
  "Waiting": "Väntar",
  "Error": "Fel",
  "Your account has been deleted": "Ditt konto har raderats",
  "The link has been sent to your email": "Länken har skickats till din e-post",
  "successful": "framgångsrik",
  "User not found": "Användaren hittades inte",
  "Something went wrong": "Något gick fel",
  "Create Your System": "Skapa ditt system",
  "Login": "Logga in",
  "Don't have an account? ": "Har inget konto? ",
  "You have an account? ": "Du har ett konto? ",
  "Sign in with Email and Password": "Logga in med e-post och lösenord",
  "Rest password": "Återställ lösenord",
  "Register Now": "Registrera nu",
  "Click to login": "Klicka för att logga in",
  "Enter Your Email": "Skriv in din e-postadress",
  "Email": "E-post",
  "Password": "Lösenord",
  "Enter Your country": "Ange ditt land",
  "Forgot password": "glömt ditt lösenord",
  "Login with Google": " Logga in med Google ",
  "Enter Your Password": "Ange ditt lösenord",
  "Privacy Policy": "Integritetspolicy",
  "Terms & Conditions": "Allmänna & Villkor",
  "Totel Users": "Totalt antal användare: ",
  "Totel Invoices": "Totala fakturor: ",
  "Copyright": "upphovsrätt 2022",
  "All rights Reserved": "Alla rättigheter förbehållna",
  "Please enter email": "Vänligen ange e-post",
  "please enter a working email address": "vänligen ange en fungerande e-postadress",
  "Please enter the password": "Vänligen ange lösenordet",
  "Please enter a valid valid password more than 8 numbers and letters": "Ange ett giltigt lösenord med fler än 8 siffror och bokstäver",
};

const Map<String, String> frFR = {
  "title_System_Ar": "title_System_Ar",
  "Swedish": "svenska",
  "Users": "Utilisateurs",
  "No Details List To Display": "Aucune liste de détails à afficher",
  "country": "pays",
  "hold": "tenir",
  "French": "Français",
  "Withdrawal": "Retrait",
  "Refund": "Remboursement",
  "deposit": "verser",
  "withdraw money": "retirer de l'argent",
  "Total hold Amount": "Montant total de la retenue",
  "ADD Users": "ajouter des utilisateurs",
  "Date created: ": "Date créée: ",
  "delete": "effacer",
  "Amount withdrawn": "Montant retiré",
  "Refunds": "Remboursements",
  "country: ": "pays: ",
  "Revenue: ": "Revenu: ",
  "details": "détails",
  "title": "Titre",
  "Email: ": "E-mail: ",
  "disable": "désactiver",
  "Phone: ": "Téléphoner: ",
  "Enter details": "Entrez les détails",
  "Send": "Envoyer",
  "Enter title": "Entrez le titre",
  "User name: ": "Nom d'utilisateur: ",
  "User Type:-": "Type d'utilisateur:-",
  "Account Status :-": "Statut du compte :-",
  "chart": "graphique",
  "Send notifications": "Envoyer des notifications",
  "No Online Support": "Pas de support en ligne",
  "Unpaid": "Non payé",
  "There are no Users": "Il n'y a pas d'utilisateurs",
  "Return": "Revenir",
  "Search": "Chercher",
  "In Review": "En revue",
  "#Reference Number: ": "# Numéro de réference: ",
  "Total Invoice : ": "Facture totale : ",
  "Pay Done": "Betala Klar",
  "Total Today:": "Totalt idag: ",
  "You have no invoices": "Du har inga fakturor",
  "You have no notifications": "Du har inga aviseringar",
  "Dashboard/Notifications": "Instrumentpanel/Aviseringar",
  "Enter Your Full Name": "Ange ditt fullständiga namn",
  "Full Name": "Fullständiga namn",
  "Team management": "Laghantering",
  "System setting": "Systeminställning",
  "Phone Number": "Telefonnummer",
  "Enter Your Phone Number": "Skriv in ditt telefonnummer",
  " MASTAR": " INFINITIV",
  "Account Status :": "Konto Status :",
  " ADMIN": "ADMINISTRATION",
  " USER": " ANVÄNDARE",
  " Active": " Aktiva",
  "Disabled": "Inaktiverad",
  "Active": "Aktiva",
  "Deleted": "raderade",
  " Under review": "  Under granskning",
  "Notifications": "Aviseringar",
  "Settings": "inställningar",
  "User ID: ": "användar ID: ",
  "Delete Account": "Radera konto",
  "Profile": "Profil",
  "Status:": "Status:",
  "/Profile": "/Profil",
  "Support": "Stöd",
  "Dashboard/Profile": "Instrumentpanel/profil",
  "Support/Profile": "Stöd/Profil",
  "Dashboard": "instrumentbräda",
  "English": "engelsk",
  "Something went wrong! Please try again later": "Något gick fel! Vänligen försök igen senare",
  "created successfully, Your account in now under review": "skapat framgångsrikt, Ditt konto granskas nu",
  "Qty": "Antal",
  "Arabic": "arabiska",
  "the email is already used": "e-postmeddelandet är redan använt",
  "Account temporarily locked": "Kontot är tillfälligt låst",
  "Wrong password": "Fel lösenord",
  "Your account has been disabled": "ditt konto har avaktiverats",
  "Pay": "Betala",
  "Payment Done!": "Betalning gjord!",
  "Merchent Name": "handlarens namn : ",
  "Invoice To :": "Fakturera till :",
  "invoice date :": "fakturadatum :",
  "discount %": "rabatt %",
  "description": "beskrivning",
  "ADD Details": "LÄGG TILL Detaljer",
  "Total: ": "Total: ",
  "Click on Plus Icon (+) to add new Details": "Klicka på plusikonen (+) för att lägga till nya detaljer",
  "Confirm Details": "Bekräfta detaljer",
  "Enter country": "Ange land",
  "username": "Användarnamn",
  "Enter username": "Skriv in ditt användarnamn",
  "balance": "balans",
  "Log out": "Logga ut",
  "Register Team account": "Registrera Team-konto",
  "Wallet": "Plånbok",
  "Amounts available": "Tillgängliga mängder",
  "Please enter mobile phone number": "Vänligen ange mobilnummer",
  "Please enter a valid mobile phone number": "Vad vänlig och skriv in ett giltigt mobilnummer",
  "title_System_EN": "title_System_EN",
  "ADS": "annonser",
  "Please enter the value": "Ange värdet",
  "Last 7 days": "Senaste 7 dagarna",
  "Months": "månader",
  "Years": "år",
  "Enter Your Client Email": "Ange din kunds e-postadress",
  "name": "namn",
  "Enter Your Client name": "Ange ditt kundnamn",
  "Price": "Pris",
  "Enter Your Price": "Ange ditt pris",
  "Advanced invoice": "Avancerad faktura",
  "phone": "telefon",
  "quick invoice": "snabb faktura",
  "Enter Your Client phone": "Ange din klienttelefon",
  "Create Invoice": "Skapa faktura",
  "Save": "Spara",
  "Merchant Name": "handlarens namn",
  "Number VAT": "Antal moms",
  "Enter Your VAT %": "Ange din momsprocent %",
  "VAT %": "MOMS %",
  "Enter Your Merchant Name": "Ange ditt säljarnamn",
  "review": "recension Acc",
  "Enter Your Number VAT": "Ange ditt nummer moms",
  "Please enter all fields": "Vänligen fyll i alla fält",
  "Camera": "Kamera",
  "Gallery": "Galleri",
  "Change Language": "Ändra språk",
  "Waiting": "Väntar",
  "Error": "Fel",
  "Your account has been deleted": "Ditt konto har raderats",
  "The link has been sent to your email": "Länken har skickats till din e-post",
  "successful": "framgångsrik",
  "User not found": "Användaren hittades inte",
  "Something went wrong": "Något gick fel",
  "Create Your System": "Skapa ditt system",
  "Login": "Logga in",
  "Don't have an account? ": "Har inget konto? ",
  "You have an account? ": "Du har ett konto? ",
  "Sign in with Email and Password": "Logga in med e-post och lösenord",
  "Rest password": "Återställ lösenord",
  "Register Now": "Registrera nu",
  "Click to login": "Klicka för att logga in",
  "Enter Your Email": "Skriv in din e-postadress",
  "Email": "E-post",
  "Password": "Lösenord",
  "Enter Your country": "Ange ditt land",
  "Forgot password": "glömt ditt lösenord",
  "Login with Google": " Logga in med Google ",
  "Enter Your Password": "Ange ditt lösenord",
  "Privacy Policy": "Integritetspolicy",
  "Terms & Conditions": "Allmänna & Villkor",
  "Totel Users": "Totalt antal användare: ",
  "Totel Invoices": "Totala fakturor: ",
  "Copyright": "upphovsrätt 2022",
  "All rights Reserved": "Alla rättigheter förbehållna",
  "Please enter email": "Vänligen ange e-post",
  "please enter a working email address": "vänligen ange en fungerande e-postadress",
  "Please enter the password": "Vänligen ange lösenordet",
  "Please enter a valid valid password more than 8 numbers and letters": "Ange ett giltigt lösenord med fler än 8 siffror och bokstäver",
};

