// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyAuxb1Me_eWBAXKtTPf77kFEMkaijjSP_I",
      authDomain: "invoice-system-flutter.firebaseapp.com",
      projectId: "invoice-system-flutter",
      storageBucket: "invoice-system-flutter.appspot.com",
      messagingSenderId: "500159637805",
      appId: "1:500159637805:web:2ec3427edd51cf6288cba4",
      measurementId: "G-8LELRJN41Y"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwTMiKHd5vVGo_J_a_TGWax-5eJ2DcVR4',
    appId: '1:597080263377:android:84199ecb8aa796b6fe13f0',
    messagingSenderId: '597080263377',
    projectId: 'electoronic-payments',
    storageBucket: 'electoronic-payments.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNc6U_KiwA7JWfxBobCH1Z54WKXQDbDGc',
    appId: '1:597080263377:ios:98eacdc003835425fe13f0',
    messagingSenderId: '597080263377',
    projectId: 'electoronic-payments',
    storageBucket: 'electoronic-payments.appspot.com',
    iosClientId: '597080263377-f3k04fh959c0ujk4shkdqn2i52d9pos2.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNc6U_KiwA7JWfxBobCH1Z54WKXQDbDGc',
    appId: '1:597080263377:ios:98eacdc003835425fe13f0',
    messagingSenderId: '597080263377',
    projectId: 'electoronic-payments',
    storageBucket: 'electoronic-payments.appspot.com',
    iosClientId: '597080263377-f3k04fh959c0ujk4shkdqn2i52d9pos2.apps.googleusercontent.com',
    iosBundleId: 'com.example.invoice',
  );
}
